# Generated by Django 4.0.3 on 2022-04-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='active',
            new_name='status',
        ),
    ]
