# Generated by Django 4.0.3 on 2022-04-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pick_up', models.CharField(blank=True, max_length=500, null=True)),
                ('drop', models.CharField(blank=True, max_length=500, null=True)),
                ('prefer_car', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_of_jorney', models.IntegerField(blank=True, null=True)),
                ('commission_of_vendor', models.IntegerField(blank=True, null=True)),
                ('date_of_jorney', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('is_pickup', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComfirmBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_booking_confirm', models.BooleanField(default=False)),
                ('driver_name', models.CharField(blank=True, max_length=500, null=True)),
                ('driver_email', models.CharField(blank=True, max_length=500, null=True)),
                ('driver_mobile_number', models.CharField(blank=True, max_length=500, null=True)),
                ('driver_licence_number', models.CharField(blank=True, max_length=500, null=True)),
                ('driver_vehicle_number', models.CharField(blank=True, max_length=500, null=True)),
                ('postbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.postbooking')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
